version: '3.8'
services:
    discord-autoclient:
        image: discord-autoclient:latest
        init: true
        user: seluser
        build:
            context: .
            dockerfile: Containerfile
        environment:
            - BROWSER_PATH=/opt/google/chrome/chrome
            - PROFILES_PATH=/home/seluser/profiles
        volumes:
            - chromium_profiles:/home/seluser/profiles
            - ./accounts.json:/data/accounts.json:ro
            - ./avatars:/data/avatars:ro

volumes:
    chromium_profiles:
